set(XKBFILE_PATH "${IMPORTEDDIR}/third/libxkbfile-1.1.0")

set(XKBFILE_INCLUDE_DIR "${XKBFILE_PATH}/include")
set(XKBFILE_LIB_DIR "${XKBFILE_PATH}/lib")
set(XKBFILE_CFLAG "-I${XKBFILE_INCLUDE_DIR} ")
set(XKBFILE_LIB "-L${XKBFILE_LIB_DIR} -lxkbfile ")

string(APPEND XSERVERCFLAGS_CFLAGS ${XKBFILE_CFLAG})
string(APPEND XSERVERCFLAGS_LIBS ${XKBFILE_LIB})
string(APPEND XSERVERLIBS_CFLAGS ${XKBFILE_CFLAG})
string(APPEND XSERVERLIBS_LIBS ${XKBFILE_LIB})
