set(PIXMAN_PATH "${IMPORTEDDIR}/third/pixman-0.40.0")



set(PIXMAN_INCLUDE_DIR "${PIXMAN_PATH}/include/pixman-1")
set(PIXMAN_LIB_DIR "${PIXMAN_PATH}/lib")


set(PIXMAN_CFLAG "-I${PIXMAN_INCLUDE_DIR} ")
set(PIXMAN_LIB "-L${PIXMAN_LIB_DIR} -lpixman-1 ")


string(APPEND XSERVERCFLAGS_CFLAGS ${PIXMAN_CFLAG})
string(APPEND XSERVERCFLAGS_LIBS ${PIXMAN_LIB})
string(APPEND XSERVERLIBS_CFLAGS ${PIXMAN_CFLAG})
string(APPEND XSERVERLIBS_LIBS ${PIXMAN_LIB})
