if(TARGET XSERVER)
	return()
endif()

get_filename_component(XSERVER_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}" ABSOLUTE)
get_filename_component(XSERVER_LIB_DIR "${CMAKE_CURRENT_LIST_DIR}/../" ABSOLUTE)
get_filename_component(XSERVER_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/../include" ABSOLUTE)

message("CMAKE_CURRENT_LIST_DIR : ${CMAKE_CURRENT_LIST_DIR}")
message("XSERVER_CMAKE_DIR : ${XSERVER_CMAKE_DIR}")
message("XSERVER_LIB_DIR : ${XSERVER_LIB_DIR}")
message("XSERVER_INCLUDE_DIR : ${XSERVER_INCLUDE_DIR}")


$Create imported target XSERVER
add_library(xserver SHARED IMPORTED)

message("IMPORTED_LOCATION : ${XSERVER_LIB_DIR}/${CMAKE_SHARED_LIBRARY_PREFIX}drm${CMAKE_SHARED_LIBRARY_SUFFIX}")
set_target_properties(xserver PROPERTIES
	IMPORTED_LINK_INTERFACE_LANGUAGES "C"
	IMPORTED_LOCATION "${XSERVER_LIB_DIR}/${CMAKE_SHARED_LIBRARY_PREFIX}drm${CMAKE_SHARED_LIBRARY_SUFFIX}"
	#INTERFACE_INCLUDE_DIRECTORIES "${_XSERVER_INCLUDE_DIR"
	#	INTERFACE_INCLUDE_DIRECTORIES "${_XSERVER_INCLUDE_DIR}/xserver"
	)

mark_as_advanced(XSERVER_LIB_DIR XSERVER_INCLUDE_DIR)
